### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by lakshits11** [hwittenborn/makedeb#273] opened 2023-07-19 13:52 UTC
### Issue

on using the installation script, I get the following output.
```
lakshit@lakshit ~> bash -ci "$(wget -qO - 'https://shlink.makedeb.org/install')"
-------------------------
[#] makedeb Installer [#]
-------------------------

[>] Ensuring needed packages are installed...
Hit:1 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:2 http://packages.microsoft.com/repos/code stable InRelease                                                                                   
Hit:3 https://deb.nodesource.com/node_18.x bullseye InRelease                                                                                     
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease                                                                                     
Hit:5 http://deb.debian.org/debian bullseye InRelease                                                                                             
Hit:6 https://packages.microsoft.com/repos/edge stable InRelease                                                                                  
Hit:7 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                     
Get:9 http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11  InRelease [1,556 B]                                           
Hit:10 http://mx-pkg.mirror.net.in/MX-Linux/mx/repo bullseye InRelease
Err:11 https://proget.makedeb.org makedeb InRelease                  
  502  Bad Gateway [IP: 104.237.134.92 443]
Hit:8 https://apt.llvm.org/bullseye llvm-toolchain-bullseye-15 InRelease
Hit:12 http://security.debian.org/debian-security bullseye-security InRelease
Hit:13 https://non-gnu.uvt.nl/debian bullseye InRelease
Fetched 1,556 B in 7s (236 B/s)                                                                                                                   
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://brave-browser-apt-release.s3.brave.com stable InRelease' doesn't support architecture 'i386'
W: Failed to fetch https://proget.makedeb.org/dists/makedeb/InRelease  502  Bad Gateway [IP: 104.237.134.92 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

[>] Multiple releases of makedeb are available for installation.
[>] Currently, you can install one of 'makedeb', 'makedeb-beta', or
[>] 'makedeb-alpha'.
[?] Which release would you like? makedeb-alpha

[>] Setting up makedeb APT repository...
gpg: no valid OpenPGP data found.
[>] Updating APT cache...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease                                                                                     
Hit:3 http://deb.debian.org/debian bullseye InRelease                                                                                             
Hit:4 https://brave-browser-apt-release.s3.brave.com stable InRelease                                                                             
Hit:5 https://deb.nodesource.com/node_18.x bullseye InRelease                                                                                     
Hit:6 http://packages.microsoft.com/repos/code stable InRelease                                                                                   
Hit:7 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                     
Hit:8 https://packages.microsoft.com/repos/edge stable InRelease                                                                                  
Get:10 http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11  InRelease [1,556 B]                                          
Hit:11 https://non-gnu.uvt.nl/debian bullseye InRelease             
Hit:12 http://mx-pkg.mirror.net.in/MX-Linux/mx/repo bullseye InRelease     
Hit:9 https://apt.llvm.org/bullseye llvm-toolchain-bullseye-15 InRelease   
Err:13 https://proget.makedeb.org makedeb InRelease                 
  502  Bad Gateway [IP: 104.237.134.92 443]
Fetched 1,556 B in 4s (440 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://brave-browser-apt-release.s3.brave.com stable InRelease' doesn't support architecture 'i386'
W: Failed to fetch https://proget.makedeb.org/dists/makedeb/InRelease  502  Bad Gateway [IP: 104.237.134.92 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

[>] Installing 'makedeb-alpha'...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package makedeb-alpha
[!] Failed to install package.
exit
```

### Installation source

APT Repository

### Installed release type

Alpha

### Installed makedeb version

NA

**Comment by razzius** [comment] 2023-12-28 06:10
It seems to be working for me right now, but to me this kind of issue is why such a package should itself be packaged as a deb and hosted and mirrored in official repos :)

**Comment by ghost** [comment] 2024-03-11 23:05
@hwittenborn 
the mpr is down again

**Comment by hwittenborn** [comment] 2024-03-11 23:25
@lakshits11: Are you still experiencing the issue? makedeb's ProGet instance is up and running, so everything should be working fine. I'm going ahead and closing this for the time being, but feel free to reach out if you're still having trouble.

The issue you were facing appears to be something else @pirate486743186, but it should now be resolved. I was doing some tests yesterday on my server (it's hosted at my school, and I was making sure everything was correct before going home), and this appeared to get messed up as a result of that. I have a status monitor that checks things every minute, but all my other services temporarily went down as part of my testing, and I hadn't seen that the MPR failed to come back online as a result. Everything should be good from this point though.

**Closed as completed by hwittenborn** 2024-03-11 23:25 UTC
Labels: T-Defect

**Comment by ghost** [comment] 2024-03-25 19:23
@hwittenborn  
broken again
404 page not found

**Comment by hwittenborn** [comment] 2024-03-26 03:38
Hey @pirate486743186, I can confirm that something was going on but things should be fine now. I'm not really sure what's causing this, but I'm actively looking into it to find out what may be going on.

**Comment by ghost** [comment] 2024-05-14 17:24
@hwittenborn 
Urgent
Now it's `502 Bad Gateway` again

Should i keep reporting this when it happens?

**Comment by ghost** [comment] 2024-09-17 21:01
@hwittenborn
server down again `404 page not found`
